# Generated by Django 5.2.12 on 2026-04-20 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_budget', '0001_initial'),
        ('netbox_digital_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='netbox_budget.tender'),
        ),
        migrations.AddField(
            model_name='license',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='netbox_budget.tender'),
        ),
    ]
