# Generated by Django 5.2.12 on 2026-06-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_digital_assets', '0002_certificate_tender_license_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
