# Generated by Django 5.2.12 on 2026-06-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_digital_assets', '0003_contract_comments_supplier_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='license',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
